### ISSUE TITLE
Wrong address gives error

### ISSUE THREAD

**Issue by radius314** [radius314/yap#106]
**Describe the bug**
If you enter an incorrect zip code / or location the retry message doesn't play

**What version are you running**
latest unstable (post-2.0.0)

**To Reproduce**
1. Search for meetings or someone to talk to.
2. Press 2 for zip code
3. Enter 27595 (invalid zip code)
4. You should get an invalid URL error in the Twilio console.

**Expected behavior**
Should play an error message and give an opportunity to retry.

**Comment by DeathCamel58** [comment]
Dialing 00000 for our help line just pulls up the United States of America. No error. `$location_lookup_bias` is set to `us`, so that might affect it.

**Comment by radius314** [comment]
I assumed this was an invalid zip code.  Just enter a zip code that does not exist.

**Comment by radius314** [comment]
the patch for this was pushed to unstable last night https://github.com/radius314/yap/commit/8155f191e3c9f6e927e8610018dd66abbec89866, untested
