### ISSUE TITLE
helpline called with no volunteer on schedule rings forever

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#107]
**Describe the bug**
if you call the helpline and no volunteer is on the schedule the call just rings forever

**What version are you running**
latest master 2.0

**To Reproduce**
Remove volunters from a specific time and try calling.

**Expected behavior**
if voicemail is set, it should go straight to voicemail. if not some sort of message, maybe even txt to helpline chair if thats set to let them know.

**Comment by radius314** [comment]
As a possible workaround, what happens if you put an invalid phone number, say `5555551212`?

**Comment by pjaudiomv** [comment]
I actually created this issue with a human error expectation in mind. If for some reason no one is set on the schedule. The sick and suffering addict just doesn't get sent into space forever wether that be a transfer to a fallback number or voicemail.
