### ISSUE TITLE
getMeetings API

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#109]
**Describe the bug**
I may be misunderstanding how this works so it may be more of a question than a bug. It seems the getMeetings API isnt respecting the results_count

https://bmlt.charlestonna.org/yap3/api/getMeetings.php?latitude=41.363871&longitude=-70.5502916&results_count=4

this returns 7 meetings, I think it should be four

https://bmlt.charlestonna.org/yap3/api/getMeetings.php?latitude=41.363871&longitude=-70.5502916&results_count=10

this returns 60 meetings, should be 10

getServiceBodyCoverage works great!

**What version are you running**
Latest Master 2.0.1

**Comment by pjaudiomv** [comment]
bmlt seems to respect this
https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&long_val=-70.5502916&lat_val=41.363871&page_size=5

**Comment by pjaudiomv** [comment]
guess if i can get the info from bmlt i dont need to use yaps API for that kind of query if i know what server i want

**Comment by radius314** [comment]
Will look at this later

**Comment by pjaudiomv** [comment]
Damn thanks, good thinking.
