### ISSUE TITLE
When logging in with multiple credentials I'm not seeing all service bodies in volunteers

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#111]
**Describe the bug**
I have multiple logins, one gives me access to two regions and one just a single area. When I login with the multiple service body login I only see the one asc and not the multiple regions and asc. When I login with single asc login everything is fine. I see the multiple service bodies in the service bodies tab. When I save the service body settings it doesn't show up in the volunteers dropdown.

**What version are you running**
2.0.1

**To Reproduce**
1. Login with a credential that multiple service body permissions
2. Add multiple service bodies
3. Click on volunteer tab and see if those service bodies are in the dropdown

**Expected behavior**
All service bodies that are active show up in the volunteer drop down

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/43085594-f6e7811c-8e60-11e8-8f72-a1087c8f75ed.png)

![image](https://user-images.githubusercontent.com/31661648/43085608-042c3638-8e61-11e8-8f33-ae6d6e157841.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Firefox
 - Version 61.0.1

**Comment by californiasteve** [comment]
When I logged in to my test server with the same 2.0.1 version I'm not having this problem, hhmmm

**Comment by pjaudiomv** [comment]
Maybe there is a weird cacheing thing, open up a private browser window and try the one that's not working

**Comment by radius314** [comment]
Which service body ID do you expect to see in the volunteer routing dropdown?

**Comment by californiasteve** [comment]
Yes, set to "volunteer routing" and I expect to see "Hill Country, Greater Albuquerque and Freedom"

**Comment by radius314** [comment]
Volunteer routing is not set on Greater Alberquerque.  https://hillcountryna.org/yap-master/service-body-config.php?service_body_id=1072

**Comment by californiasteve** [comment]
I had set it just a 10 minutes ago, It must not be saving.

**Comment by radius314** [comment]
Correct, it's not saving for some reason.

**Comment by radius314** [comment]
can you email me the config.php from both instances (working vs not)

**Comment by californiasteve** [comment]
Could it be because I am logged into that server through BMLT?

**Comment by radius314** [comment]
No.

**Comment by radius314** [comment]
Maybe.

**Comment by californiasteve** [comment]
Works now after removing the trailing / from the bmlt server address.

**Comment by radius314** [comment]
K, yeah I'm gonna leave this ticket open, I had this issue the other day?

**Comment by radius314** [comment]
unable to repro.  still going to leave this open.
