### ISSUE TITLE
Ability to send Email notifications with voicemail

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#113]
**Describe the solution you'd like**
It would be nice to have the ability to send email notifications of voicemails in addition to the already existing ability to send sms. It would also be nice if the voicemail url could be included as a wav attachment in the email so it could be kept on email server, but not a show stopper.

**Additional context**
the New England Region requires trusted servants to use region emails for communication, this would keep a log of the voicemails in the trusted servant email addresses and can be passed on to the next trusted servant.

we will see if this gets any traction and if anyone else is interested in this feature request.

@californiasteve  @gutterwall  @DeathCamel58  @sfrna  @jbraswell  @brustar64  @tempsaint  @paulnagle

**Comment by tempsaint** [comment]
+1 

Email notifications, and even wav attachments would be awesome. Our current phoneline service has this feature and it's great for logging and easy listening to voicemails

**Comment by radius314** [comment]
in latest master 7e17819fd1bfd3b0f6c503734b786e7e31540a67
