### ISSUE TITLE
no volunteer on schedule rings forever issue

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#122]
**Describe the bug**
I'm having a issue where if I call the helpline and no one is on it rings forever. If I have volunteer routing enabled but i never added any volunteers therefore no _YAP_DATA_ entry created it works fine. however if the _YAP_DATA_ entry is there and its either empty or no one one the schedule it rigns forever. I swear this was working as expected as i know i tested it this way. maybe its just me

**What version are you running**
2.1.2

**To Reproduce**
1. either save a service body with no volunteers or remove volunteers form the day and try calling.
2. rings forever.

**Expected behavior**
Caller gets sent to voicemail

**Additional context**
Ref #107  im attaching two php error log files. 1. when i called in with no _YAP_DATA_ entry in the bmlt and 2. with _YAP_DATA_ entry.

[phperr_hasyapdata.txt](https://github.com/radius314/yap/files/2267490/phperr_hasyapdata.txt)
[phperr_noyapdata.txt](https://github.com/radius314/yap/files/2267491/phperr_noyapdata.txt)

**Comment by radius314** [comment]
It could be a regression.

**Comment by radius314** [comment]
According to the service body configuration right now, volunteer routing is disabled.  Did you revert this?

**Comment by pjaudiomv** [comment]
no its enabled for that body (Boston) , i can send you config if you like

**Comment by pjaudiomv** [comment]
https://phoneline.nerna.org/yap-helpline/service-body-config.php?service_body_id=2

**Comment by radius314** [comment]
patch pushed to master, please test

**Comment by pjaudiomv** [comment]
this works as expected now thank you!
