### ISSUE TITLE
Only see Twilio numbers for login used

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#123]
**Is your feature request related to a problem? Please describe.**
Yes/No, Keep other admins from seeing all numbers associated with my Twilio account.

**Describe the solution you'd like**
I have multiple yap instances setup for Regions, ASC's and Metros. I would like for the logged in user only see their Twilio number information and not all of the numbers I have for my Twilio account.

**Describe alternatives you've considered**
Open to suggestions.

**Comment by californiasteve** [comment]
Here is what every user sees.
![image](https://user-images.githubusercontent.com/31661648/44003938-744a8a36-9e20-11e8-8ace-5cbbdbc990d0.png)

**Comment by pjaudiomv** [comment]
I've thought about this as well and would also like this feature. Not sure how to do it as there is no way of knowing out service body is tied to what number with the configuration and login level that  I know of. I'm sure danny knows more :)

**Comment by radius314** [comment]
Maybe we should just kill this off.

**Comment by pjaudiomv** [comment]
Yea it is helpful as an admin to easily see but you can also just check twilio and see too.

**Comment by californiasteve** [comment]
I'm good with removing it.

**Comment by radius314** [comment]
removed in master
