### ISSUE TITLE
Phone numbers truncated in SMS messages about calls sent to volunteers

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#124]
**Describe the bug**
When a caller leaves a message the SMS sent to the caller does not include a + at the beginning of the country code and you're unable to call the number unless you manually add a + to the front of it.

EG Twilio SMS - You have a message from the X Area helpline from caller 614xxxxxxx 

To call the number in Australia you have to click on it, go to your dialer and change the number to +614xxxxxxx

Messages to volunteers about calls that are routed to them have the same issue.
Not sure if its a Twilio thing of a YAP thing.

**What version are you running**
Enter the version number. 2.1.3

**Expected behavior**
If the number included a + at the front it wouldn't require training volunteers to append the + manually.

**Smartphone (please complete the following information):**
Samsung Galaxy S8

**Comment by radius314** [comment]
@brustar64 I added a check in master for this.  if it's missing then it will add it.

**Comment by radius314** [comment]
released in yap 2.2.0
