### ISSUE TITLE
Block "Anonyous" +266696687 

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#125]
**Describe the bug**
We get a lot of calls from "Anonymous" which is displayed in Twilio as +266696687
These calls consume roughly 6 minutes of programmable voice time each time they are made as well as leaving empty voicemail messages 

**What version are you running**
2.1.3

**To Reproduce**
Its available in the voice logs

**Expected behavior**
We would like to be able to reject these anonymous calls because they just seem like nuisance or robo calls.

**Comment by radius314** [comment]
This feature is in master ready to be tested.

**Comment by pjaudiomv** [comment]
I just tried testing and couldnt get it to work, although it could very well be because the number i was calling from is a verified number

**Comment by radius314** [comment]
Need a bit more info than that.

**Comment by radius314** [comment]
I just pushed two patches to master.  Be sure to include + at the beginning of the number in the blocklist.

**Comment by pjaudiomv** [comment]
cool sorry i was going through my logs trying to get more info than "this doesnt work" ha. but just tested and works as expected now. I get The number you have dialed is not a working number.

**Comment by radius314** [comment]
cool

**Comment by radius314** [comment]
@brustar64 please test as well

**Comment by radius314** [comment]
released in yap 2.2.0
