### ISSUE TITLE
More fields for volunteer info

### ISSUE THREAD

**Issue by Redguy1959** [radius314/yap#127]
Our current Helpline Volunteer database contains the following information beyond the volunteer name and phone number:

Clean Date
Sex
Other languages spoken
City
ZipCode
EMail address

Anyway to add these so we only have one database to maintain?

**Comment by Redguy1959** [comment]
A database import/export feature would also be very useful.

**Comment by radius314** [comment]
Why would Clean Date, City + Zip Code matter?

**Comment by radius314** [comment]
Not sure what you mean about import/export.  What is the use case?

Also, what do you mean by one database?

**Comment by Redguy1959** [comment]
Clean date matters because we have a policy in NJ. 
  ----- Original Message ----- 
  From: Danny Gershman 
  To: radius314/yap 
  Cc: Redguy1959 ; Author 
  Sent: Tuesday, August 28, 2018 1:14 PM
  Subject: paul@freedomweb.net - Re: [radius314/yap] More fields for volunteer info (#127) - Email found in subject


  Why would Clean Date, City + Zip Code matter?

**Comment by radius314** [comment]
That doesn't answer my question.  All data in Yap is part of some kind of operational function.  What is the functional use of these data points?

**Comment by Redguy1959** [comment]
We have a Helpline Volunteer database on our current system with about 120 volunteers in it. We would like to be able to bring that into Yap without typing it in.


  ----- Original Message ----- 
  From: Danny Gershman 
  To: radius314/yap 
  Cc: Redguy1959 ; Author 
  Sent: Tuesday, August 28, 2018 1:15 PM
  Subject: paul@freedomweb.net - Re: [radius314/yap] More fields for volunteer info (#127) - Email found in subject


  Not sure what you mean about import/export. What is the use case?

  Also, what do you mean by one database?

**Comment by radius314** [comment]
Ok as a general guide, please do not couple feature requests into the same ticket.  It will create confusion.

**Comment by Redguy1959** [comment]
Delete the request.
  From: Danny Gershman 
  To: radius314/yap 
  Cc: Redguy1959 ; Author 
  Sent: Tuesday, August 28, 2018 2:01 PM
  Subject: paul@freedomweb.net - Re: [radius314/yap] More fields for volunteer info (#127) - Email found in subject


  That doesn't answer my question. All data in Yap is part of some kind of operational function. What is the functional use of these data points?

**Comment by Redguy1959** [comment]
Import feature only then.
  ----- Original Message ----- 
  From: Danny Gershman 
  To: radius314/yap 
  Cc: Redguy1959 ; Author 
  Sent: Tuesday, August 28, 2018 2:02 PM
  Subject: paul@freedomweb.net - Re: [radius314/yap] More fields for volunteer info (#127) - Email found in subject


  Ok as a general guide, please do not couple feature requests into the same ticket. It will create confusion.

**Comment by radius314** [comment]
Please create a separate ticket for that request. 

Are these metadata fields (like notes)?  Would a single field that would be completely unfunctional be helpful?  Keep in mind this would be schemaless.

**Comment by radius314** [comment]
generic notes field added to `master` will be in the next release.

**Comment by Redguy1959** [comment]
Thanks, that will work.
  ----- Original Message -----

**Comment by radius314** [comment]
released in yap 2.2.0
