### ISSUE TITLE
Anonymous block doesn't work

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#132]
**Describe the bug**
Calls are still received and processed by Twilio.
Errors are generated in Twilio.

Msg | "The 'To' number is not a valid phone number."
-- | --
ErrorCode | "21211"
To | ""
LogLevel | "ERROR"

**What version are you running**
2.2.0
**To Reproduce**
1. Hide phone number on mobile and call the YAP enabled number
2. call is received and processed as per normal
3. No SMS is received but this is expected

**Expected behavior**
I thought the new Blocked number feature would actually stop the call from being processed by Twilio.
We are getting a lot of call time generated by Anonymous numbers.  It was hoped that this feature would allow us to block these calls.

**Comment by pjaudiomv** [comment]
hmm i wonder if you take the + away if itll work
static $blocklist = "266696687";
I found this
https://support.twilio.com/hc/en-us/articles/223179988-Why-am-I-getting-calls-from-these-strange-numbers-

**Comment by pjaudiomv** [comment]
curious, is this just a test number you provisioned. or an existing helpline number that's in use. If its just a test number I would suggest dropping it and provissioning a new number as you could get less anonymous calls.

**Comment by radius314** [comment]
It’s an actual number I believe.

**Comment by pjaudiomv** [comment]
I just tried calling using *67 and the number in my missed calls was +266696687, I put it in my block list doing the following and it blocked me so worked.

static $blocklist = "+266696687";

**Comment by radius314** [comment]
Because we are using <Reject/> there should be no charge.

**Comment by pjaudiomv** [comment]
yea no charge as we use the reject verb

**Comment by brustar64** [comment]
Apologies I must have had the config wrong.
It does work.  I hid my number on my handset and was unable to call.  It gave me a please check the number and dial again.  I need to ratify with our region as to whether or not this is viable.
Addicts (especially still using ones) can be extremely paranoid and may hide their number as a standard practice.  We don't want this stopping them from using the service even if its depreciated with a hidden number (no callback possibility or SMS can be supplied).  
Wondering if a prompt saying "We will be unable to sms you details until you unhide your number or call back from a recognised mobile service." if the number comes through as anonymous...

**Comment by radius314** [comment]
The prompt is coming from the carrier,  in order to customize that prompt we’d ha e to answer and perform a custom mp3 playback, but this would cost you for each call, and defeat the purpose of blocking that you are trying to achieve.

**Comment by radius314** [comment]
Also you are using non recorded prompts to playback a rather lengthy
message.  Have you tried converting this to a recorded message?

**Comment by brustar64** [comment]
Yes we are definitely playing a prerecorded message now.
Have been since just prior to 2.2.0.

Cheers
________________________________

**Comment by brustar64** [comment]
What I'll do is include the information about the service in the intro.
IE.
This service will not be able to send you an SMS if you call from a hidden number or a land line.

**Comment by radius314** [comment]
Not sure I understand the last sentence of your last comment.  Is this a
statement or a question or something else?

**Comment by brustar64** [comment]
This is a statement in response to the comment about using a long intro message.
________________________________
