### ISSUE TITLE
Timezone change does not save for volunteers in a different timezone

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#138]
**Describe the bug**
Setting up volunteers for an Area in a different Time Zone from me. (Brisbane comes up by default on the list but I change it to Melbourne for each shift I'm adding).  However after the shift is saved it shows up as Brisbane timezone. 

**What version are you running**
2.2.0

**To Reproduce**
1. Go to 'Add Shift'
2. add in the shift hours and change the timezone to Melbourne
3. click save
4. Shift saves with a Brisbane Timezone 

**Expected behavior**
Expect the timezone to remain as the one selected before saving

**Screenshots**
![timezone error](https://user-images.githubusercontent.com/29008815/45592771-fb3d7f80-b9b9-11e8-874b-c1943320651f.PNG)
![shiftbugtimezone](https://user-images.githubusercontent.com/29008815/45592773-009aca00-b9ba-11e8-87e8-6f1e7b036b67.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [68.0.3440.106]

**Comment by radius314** [comment]
Looks like it only happens with the Add Shift (single shift) and not Add 24/7 shifts.

**Comment by radius314** [comment]
fix was just pushed to master

**Comment by radius314** [comment]
Released with 2.2.2
