### ISSUE TITLE
Schema Validation warning

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#150]
**Describe the bug**
Twilio is reporting Schema Validation warnings
__________________________________________________________________________________________
Msg | "XML Validation warning"
-- | --
line | "2"
parserMessage | " Invalid content was found starting with element 'Message'. One of '{Play"
ErrorCode | "12200"
cols | "416"
LogLevel | "WARN"
url | "https://na.org.au/yap2/meeting-search.php?Latitude=-33.8688197&Longitude=151.2092955&Called=%2B61488811247&ToState=&CallerCountry=AU&Direction=inbound&CallerState=&ToZip=&CallSid=CAcbd5612411b8d0e2d30969f9fd7a07b3&To=%2B61488811247&CallerZip=&ToCountry=AU&ApiVersion=2010-04-01&CalledZip=&CalledCity=&CallStatus=in-progress&From=%2B61435748624&AccountSid=AC2647d8d1c20a4eaf4f7f1af2f05661da&CalledCountry=AU&CallerCity=&Caller=%2B61435748624&FromCountry=AU&ToCity=&FromCity=&CalledState=&FromZip=&FromState="

Msg | "XML Validation warning"
-- | --
line | "2"
parserMessage | " Invalid content was found starting with element 'Message'. One of '{Play"
ErrorCode | "12200"
cols | "419"
LogLevel | "WARN"
url | "https://na.org.au/yap2/meeting-search.php?Latitude=-27.4500534&Longitude=153.0345152&Called=%2B61488811247&ToState=&CallerCountry=AU&Direction=inbound&CallerState=&ToZip=&CallSid=CA86582ac53759b1e49a045757b9c39482&To=%2B61488811247&CallerZip=&ToCountry=AU&ApiVersion=2010-04-01&CalledZip=&CalledCity=&CallStatus=in-progress&From=%2B61411607551&AccountSid=AC2647d8d1c20a4eaf4f7f1af2f05661da&CalledCountry=AU&CallerCity=&Caller=%2B61411607551&FromCountry=AU&ToCity=&FromCity=&CalledState=&FromZip=&FromState="

________________________________________________________________________________________________________

**What version are you running**
2.3.1

**To Reproduce**
Search for a meeting - warnings appear in Twilio
No SMS with the meeting information is sent even though it is configured to.

**Expected behavior**
Expect an SMS with meeting information to be sent (and no error generated)

**Screenshots**

![image](https://user-images.githubusercontent.com/29008815/46350368-f48c5900-c697-11e8-833a-3d6f35eb1ee1.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android P
 - Chrome (stock browser
 - Version NA (not a browser issue)

**Additional context**
Errors started with V2.3.1 installation

**Comment by radius314** [comment]
I hit a similar issue yesterday

**Comment by radius314** [comment]
Gonna open a ticket with Twilio, in the meantime, this is a `WARNING`, not an `ERROR`, so it should not degrade any functionality.

**Comment by radius314** [comment]
Going to swap this out with the API call as @pjaudiomv had originally suggested.

**Comment by brustar64** [comment]
But we're not getting an SMS with meeting info even though:

static $sms_ask = false;
static $include_map_link = true;

**Comment by radius314** [comment]
yes, SMS is failing right now

**Comment by radius314** [comment]
Twilio is confirming this is a bug on their side.  I'm going to be rolling back <Message> TwiML.

**Comment by brustar64** [comment]
So I should switch back to our previous version in the meantime to maintain functionality?

**Comment by radius314** [comment]
Pushing out 2.3.2 in a moment

**Comment by radius314** [comment]
2.3.2 is released, fixes this issue: https://github.com/radius314/yap/releases/tag/2.3.2

**Comment by brustar64** [comment]
All good now - thanks Danny!
Awesome support!
