### ISSUE TITLE
fallback or error catching for wrong speech pattern

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#155]
**Is your feature request related to a problem? Please describe.**
Now that speech entry is allowed, im starting to get errors, where people are saying "zip code" instead of "2". It would be nice if there was a retry or notice that said something like "wrong entry please press or say 1, 2 etc". Now the call just ends with an error. really anything besides error ending the call would be fine.

this is error I found. 

Error - 11100
Invalid URL format
<Response>
    <Redirect method="GET">zip-input.php?SearchType=2&amp;InputMethod=**zip code**</Redirect>
</Response>

**Comment by radius314** [comment]
pushed something to `master`, doesn't handle infinite searching yet

**Comment by pjaudiomv** [comment]
word thanks, this works great.

**Comment by pjaudiomv** [comment]
only thing with this now, is the JFT is a prompt for all menus now. not a big deal, but woul dbe better if helpline/meeting lookup only had the two propmts for zip code/city

**Comment by radius314** [comment]
This is not anything new that you’re bringing up

**Comment by pjaudiomv** [comment]
gotcha
