### ISSUE TITLE
Location Lookup Bias using extra components=

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#157]
**Describe the bug**
In my logs I am getting this `components=components=country:us` where as it should just be 
`components=country:us`

**What version are you running**
2.3.2 this has been there since 2.0.0-beta3

**To Reproduce**
check php_errorlog of yap instance

**Expected behavior**
url should just contain `components=country:us` for default

**Log**
`&address=Sandwich+Mass%2C+MA&components=components%3Dcountry%3Aus
&address=02767&components=components%3Dcountry%3Aus`

**Additional context**
I submitted PR for fix here, default lookup bias fix #156

this was leaving `components=components=country:us` in my logs where as it should just be 

API Spec
 https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering

**Comment by radius314** [comment]
What's in your config.php?

**Comment by pjaudiomv** [comment]
`
static $title = "Welcome New England Region of Narcotics Anonymous";
static $bmlt_root_server = "https://tomato.na-bmlt.org/main_server";
static $helpline_bmlt_root_server = "https://phoneline.nerna.org/main_server";
static $google_maps_api_key = "API_KEY";
static $twilio_account_sid = "twilio_account_sid";
static $twilio_auth_token = "twilio_auth_token ";
static $bmlt_username = "patrickj";
static $bmlt_password = "PASSWORD";
static $voice = "Polly.Joanna";
static $en_US_greeting = 
"https://phoneline.nerna.org/recordings/region_welcome.mp3";
static $meeting_search_radius = 25;
static $result_count_max = 4;
static $infinite_searching = true;
static $sms_ask = true;

static $smtp_host = 'smtp.gmail.com:587';             // the smtp server
static $smtp_username = 'pjaudiomv@gmail.com';         // the smtp username
static $smtp_password = 'PASSWORD';         // the smtp password
static $smtp_secure = 'tls';           // either ssl (port 486) or more securely tls (port 587)
static $smtp_from_address = 'pjaudiomv@gmail.com';     // the address where the email will be sent from
static $smtp_from_name = 'Patrick J';        // the label name on the from address`

**Comment by pjaudiomv** [comment]
nothing for location lookup bias, as i want to use default, in the readme we tell people to do this as example `static $location_lookup_bias = "country:France";` so i think we should keep it that way.
https://github.com/radius314/yap#location-lookup-bias

**Comment by radius314** [comment]
Fix is in master.  You can workaround this issue without upgrading by specifying `static $location_lookup_bias = "country:us";` in your config.php

**Comment by pjaudiomv** [comment]
ok cool thanks. was there a problem with my PR?

**Comment by radius314** [comment]
No i just didn't see it.

**Comment by radius314** [comment]
In the future, if you are planning on working on a ticket, please use the "Assignees" feature to communicate that you are intending on doing so.

**Comment by pjaudiomv** [comment]
Cool yea it doesn't let me add labels or assignments

**Comment by radius314** [comment]
Let's leave the tickets open until the release happens.  I made you a collaborator, so you should be able to modify things now.  Check your email.

**Comment by pjaudiomv** [comment]
ok got it, just saw email.
