### ISSUE TITLE
Phantom Calls with a single ring coming in from the Helpline

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#159]
**Describe the bug**
Volunteers are reporting that the phone rings once then hangs up outside their scheduled time.
Call logs don't reflect this in Twilio but the phone screenshots show that calls were made to the volunteer's handset.  Several volunteers have reported that this is occurring.

**What version are you running**
2.3.2

**To Reproduce**
Unable to reproduce as its randomly happening.

**Expected behavior**
We expect Volunteers will only receive calls during their scheduled shifts.
Additionally volunteers are configured to receive an SMS when a call is routed to them but no SMS is coming with these single ring phantom calls.

**Screenshots**
Volunteer phone calls received on 15 October 2018 
![volunteer phantom calls](https://user-images.githubusercontent.com/29008815/46996368-c4e15480-d15f-11e8-92fb-140592db6daf.jpg)

Call logs from Twilio
![image](https://user-images.githubusercontent.com/29008815/46996489-2dc8cc80-d160-11e8-8aee-8148fc318859.png)

**Smartphone (please complete the following information):**
iPhone
**Additional context**
Please advise if any additional logs are required.

**Comment by pjaudiomv** [comment]
I had this happen randomly twice that I've noticed, only thing I can add is I'm last person on the call list.

**Comment by radius314** [comment]
“Call logs don't reflect this in Twilio but the phone screenshots show that calls were made to the volunteer's handset.“

These seem like two conflicting statements.  Can you clarify?

**Comment by radius314** [comment]
Some additional details

1) @pjaudiomv what version of yap had this issue?  @brustar64 I see you aren't on the latest version of yap (2.3.3).  There was an issue with the TimeZone API that was causing an issue for at least one person.  The upgrade-advisor in yap 2.3.3 would let you know if this wasn't configured properly.
2) What's the url of your yap instance that is having the issue?
3) What is the service body ID that exhibited this issue?
4) @brustar64 as @pjaudiomv mentioned that he was the last person on the shift.  In the case of this particular occurrence, is this true for this person during that time period?
5) "Additionally, volunteers are configured to receive an SMS when a call is routed to them but no SMS is coming with these single ring phantom calls." @brustar64 is this for all volunteers or just those getting the phantom calls?

Going to send more information about some logs that would help.

**Comment by pjaudiomv** [comment]
either 2.3.1 or 2.3.2 cant be sure im a do some forensic work and try to figure out more.

**Comment by radius314** [comment]
6. Can you make me a temporary user on your account?  The level of detail required to review is not exportable AFAIK. I do not need admin rights, just "Billing Manager" rights.  You should be able to add me from the top right drop down.

**Comment by radius314** [comment]
Also, to help understand the urgency of this issue, is this causing those seeking help to not be connected completely.  Or is this more of annoyance?

On Oct 16, 2018, at 10:18 AM, Danny Gershman <notifications@github.com> wrote:

Can you make me a temporary user on your account? The level of detail required to review is not exportable AFAIK. I do not need admin rights, just "Billing Manager" rights. You should be able to add me from the top right drop down.

**Comment by brustar64** [comment]
I'm only seeing version 2.3.2 on https://github.com/radius314/yap

Where is the download link for 2.3.3?

________________________________

**Comment by pjaudiomv** [comment]
If you go to branches on the top left and click tags you'll see 2.3.3
https://github.com/radius314/yap/archive/2.3.3.zip

**Comment by pjaudiomv** [comment]
https://github.com/radius314/yap/tree/2.3.3

**Comment by brustar64** [comment]
> Some additional details
> 
> 1. @pjaudiomv what version of yap had this issue?  @brustar64 I see you aren't on the latest version of yap (2.3.3).  There was an issue with the TimeZone API that was causing an issue for at least one person.  The upgrade-advisor in yap 2.3.3 would let you know if this wasn't configured properly. 
> 2. What's the url of your yap instance that is having the issue?
> 3. What is the service body ID that exhibited this issue?
> 4. @brustar64 as @pjaudiomv mentioned that he was the last person on the shift.  In the case of this particular occurrence, is this true for this person during that time period?
> 5. "Additionally, volunteers are configured to receive an SMS when a call is routed to them but no SMS is coming with these single ring phantom calls." @brustar64 is this for all volunteers or just those getting the phantom calls?
> 
> Going to send more information about some logs that would help.

Thanks

1. now on version 2.3.3 and I had a configuration issue with Timezone API not enabled.  I've now enabled this and I'm green

2. the URL is https://www.na.org.au/yap2/

3. Victoria reported the issue however I believe its actually occurred for users in other Areas (including me)

4. Victoria is configured with a single scheduled person on shift throughout the week plus a coodinator set up as an alternative at all times.  Their schedule is below:

![image](https://user-images.githubusercontent.com/29008815/47045620-9a7eae00-d1d6-11e8-911c-93d2bbc3acbc.png)

**Comment by pjaudiomv** [comment]
I am on 24hr shift as well, just mentioning as it looked she is. Don't know that related just figured the more info the better

**Comment by brustar64** [comment]
> I am on 24hr shift as well, just mentioning as it looked she is. Don't know that related just figured the more info the better

She's not on a 24 hour shift
![image](https://user-images.githubusercontent.com/29008815/47052267-fa7f4f80-d1ea-11e8-8e90-54a40a6d2370.png)

**Comment by pjaudiomv** [comment]
Ah my bad, gotcha.

**Comment by radius314** [comment]
@brustar64 did you see my comments about making me a Billing Manager on your Twilio account?  Also do you have the exact time of one of the issues?

Also is this actually affecting / preventing someone from getting connected to a volunteer? 

On Oct 16, 2018, at 7:05 PM, pjaudiomv <notifications@github.com> wrote:

Ah my bad, gotcha.

**Comment by radius314** [comment]
Can you send over the request now for the Billing Manager access?  I have a couple of hours right now to dig into it.

**Comment by brustar64** [comment]
resent invitation but bumped you to admin
________________________________

**Comment by radius314** [comment]
Ok I didn’t need admin rights, too much permission for me.

On Oct 16, 2018, at 10:14 PM, brustar64 <notifications@github.com> wrote:

resent invitation but bumped you to admin
________________________________

**Comment by brustar64** [comment]
Your role has been updated to billing manager again 😊
________________________________

**Comment by radius314** [comment]
I'm noticing a bunch of these errors in the console, that might be related to this issue: https://www.twilio.com/docs/api/errors/30005

**Comment by brustar64** [comment]
The last one of those errors was 6 days ago

We are getting multiple phantom single ring calls happening today.
More reported from Victoria...
________________________________

**Comment by radius314** [comment]
That's not the same error.

**Comment by radius314** [comment]
When did this start happening?  When was the first occurrence?  Was it associated with a version change or did it just start happening all of a sudden?

**Comment by brustar64** [comment]
It's been happening since 2.3.2 from what I understand.
Is there a way to increase the log file size?  It only seems to cover a day or two...

**Comment by radius314** [comment]
You need to contact the hosting provider about the logging question.

**Comment by radius314** [comment]
What was the actual day in which you upgraded to 2.3.2?

**Comment by radius314** [comment]
Thanks, was this issue happening prior to 2.3.2?

**Comment by radius314** [comment]
Also, what version were you on prior to 2.3.2?

**Comment by brustar64** [comment]
3.2.1 we've upgraded every time a new version was released.

Regards
Bruce

________________________________

**Comment by radius314** [comment]
you mean 2.3.1?

**Comment by radius314** [comment]
added additional logging in 2.4.0 and integration with logdna (undocumented) to assist in remote debugging.

**Comment by brustar64** [comment]
I'm really sorry for all the lack of sleep that this misreported error has caused.
The state which was transitioning to YAP are still running their local helpline service which runs from a black box was apparently causing this issue.  The new helpline coordinator assumed that the issue was related to the new YAP service but apparently its been happening for months on their old system.

I should receive the porting paperwork today and we can begin the transition to YAP completely for this state.

Thanks again for all your help on this Danny and apologies for the unnecessary stress this caused.  On the bright side we now have remote logging. 👍

**Comment by radius314** [comment]
👍 glad this wasn’t a bug.
