### ISSUE TITLE
500 error when sending an SMS with "JFT"

### ISSUE THREAD

**Issue by radius314** [radius314/yap#163]
Twilio is reporting a 500 error when sending an SMS to the sms-gateway.php.

On yap 2.4.0

**Comment by pjaudiomv** [comment]
damn it i had a fix to break messages up, but i rebased over it. thats why you use branches i guess. ill take a look at why theres 500 though. the jft must be broken up as you can only concatenate 1600 characters and sometimes the jft can exceed that.

**Comment by radius314** [comment]
a 500 is a server error, not a Twilio error.

**Comment by pjaudiomv** [comment]
yes i know

**Comment by radius314** [comment]
Ok what's the error message?

**Comment by pjaudiomv** [comment]
sorry i was talking about two different things.
but message when i just tried is as so.
 Uncaught Twilio\Exceptions\RestException: [HTTP 400] Unable to create record: The concatenated message body exceeds the 1600 character limit.

**Comment by radius314** [comment]
Ok thanks.  That 400 error is causing yap to throw the 500?

**Comment by pjaudiomv** [comment]
Warning - 12200
Schema validation warning

**Comment by radius314** [comment]
this was an error not a warning

Error - 11200

HTTP retrieval failure

**Comment by pjaudiomv** [comment]
hm, so your error seemed to have failed at retrieving the jft, and mine failed at trying to send it

**Comment by radius314** [comment]
it was an HTTP retrieval of the sms-gateway.php not retrieval of the JFT it self

**Comment by radius314** [comment]
Just debugged it, it's the same error.

**Comment by pjaudiomv** [comment]
im not seeing that, I take it your using new logging feature.

**Comment by pjaudiomv** [comment]
Ok got a fix coming

**Comment by radius314** [comment]
the fix is merged into master, slated for 2.5.0

**Comment by radius314** [comment]
released with 2.5.0
