### ISSUE TITLE
parse failure on Twilio

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#165]
**Describe the bug**
When calling in voice command and dtmf I get an error on all options from Twilio
![image](https://user-images.githubusercontent.com/31661648/47271848-92aa6b00-d542-11e8-9199-8043cfb4dc73.png)

**What version are you running**
2.4.0

**Expected behavior**
Connect to helpline volunteer, meeting finder or JFT

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/47271874-f46ad500-d542-11e8-954c-281288007009.png)

**Comment by californiasteve** [comment]
Another screenshot
![image](https://user-images.githubusercontent.com/31661648/47271894-267c3700-d543-11e8-96c6-0289b943fb3f.png)

**Comment by radius314** [comment]
Not a good idea to have phone numbers in the description.  Repro steps should work in an isolated system, not on a test system.

**Comment by radius314** [comment]
These repro steps seem incomplete.  Several people are running 2.4.0 and have not reported this issue.

**Comment by californiasteve** [comment]
I'm running different instances on the same server and not having any issues with those 2.4.0 installations, just this one. I just reuploaded all of the files again to make sure none were corrupted.

**Comment by radius314** [comment]
It’s your PHP settings most likely.

**Comment by radius314** [comment]
Downgrade to the last known working version.

**Comment by californiasteve** [comment]
back to 2.3.3 and php ver 7.0, still have issues

**Comment by radius314** [comment]
I believe I know what might be going on.  I can't repro it, but I've narrow it down to two files that have been causing this.  Can you see if `master` fixes your issue?

**Comment by californiasteve** [comment]
Works as expected now, thanks for getting it fixed.

**Comment by radius314** [comment]
Good to hear.  Will close this when 2.5.0 is officially released this week.

**Comment by radius314** [comment]
released with 2.5.0
