### ISSUE TITLE
"Add Shift" - Times not saving - Defaults to 1AM to 1AM

### ISSUE THREAD

**Issue by brustar64** [radius314/yap#167]
*Describe the bug*  

*What version are you running*  
Enter the version number. 2.4.0

*To Reproduce*  

1. Go to Volunteer
2. Click on Add Shift'
3. Set shift time and save
4. Shift time shows as 1AM to 1AM

*Expected behavior*  
if we set a time we expect the time set to save but its saving as 1AM to 1AM

*Screenshots*  

Shift set up ready to save
![image](https://user-images.githubusercontent.com/29008815/47278778-ebdfd080-d60e-11e8-9323-40f5a6e37f09.png)

After Saving:

![image](https://user-images.githubusercontent.com/29008815/47278766-d10d5c00-d60e-11e8-93ae-541c3e19ea2a.png)

**Additional context**
Workaround - add 7 day shifts and the times save correctly - just delete the days you don't need.

I originally logged issue 166 for this but it disappeared from the issues list for some reason...

**Comment by radius314** [comment]
fix is in master

**Comment by pjaudiomv** [comment]
I tested this as well works fine, im now registered using australia/melbourne timezone from 8am-2pm ha.

**Comment by radius314** [comment]
released with 2.5.0
