### ISSUE TITLE
Helpline call from option

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#19]
I've been testing out the helpline, supercool. was wondering if there was a way for when a  call is made to a helpline volunteer it can be made to look like its coming from the twilio number. I know if your a volunteer you should pick up any number that calls you in that period, but in this day in age with so many spam callers (alot of them probably being automated through twilio haha) I find some helpline volunteers may not pickup strange numbers or hit end automatically without thinking of it. if they just had the twilio number saved in their phone and they saw it call then they would be more likely to pick it up. though i guess they would then manually need to retrieve calling addicts number but still think this may be an option worth having.

**Comment by pjaudiomv** [comment]
i added callerId="617-648-7329" (which is a verified twilio number on my account) to the dial function of the helpline dialer but wasnt sure how i could easily change it between the from or to number. I recognize this may not be a feature you want to implement as sometimes less options can be better

**Comment by radius314** [comment]
Yeah Grasshopper works this way.  What number is showing up now?

**Comment by radius314** [comment]
patched in https://github.com/radius314/yap/commit/f38254ffeb6c3cde9af829897f17b89606152a0d
