### ISSUE TITLE
functions.php

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#20]
getting an error on my functions file from twilio after last nights china doll update
error 12100 Document parse failure
<br />
<b>Parse error</b>:  syntax error, unexpected ':', expecting '{' in 
<b>/home/nercna87/wp/yap/functions.php</b> on line 
<b>208</b>
<br />

and from my php error log
syntax error, unexpected ':', expecting '{' in /home/nercna87/wp/yap/functions.php on line 208

i simply removed ': array' line 202 and seems to be working ok, but i could of screwed other things up still testing

**Comment by radius314** [comment]
yeah looks like a PHP incompatibility issue.  Pushing the update.

**Comment by radius314** [comment]
good catch
