### ISSUE TITLE
sms search

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#21]
it may be nice for the sms search to automatically search for meetings the next day if no meetings are found for current day, then if no meetings are still found post the There are no other meetings found sms. as its just a quick search this may make sense. though not sure how much sms function would be used anyway

**Comment by radius314** [comment]
what is happening now?

**Comment by pjaudiomv** [comment]
now if you do a sms search it responds with "There are no other meetings for today" i think around line 40 of meeting-search.php. the sms-gateway does a type 1 meeting search for current day. seems somehow it would need to do a cycle through a type 2 meeting search for upcoming if search results = 0

**Comment by pjaudiomv** [comment]
weird my new england yap does that which is latest version but i just tried it on my charleston yap and it works fine coming up with monday results. maybe its a problem with new englands bmlt server

**Comment by radius314** [comment]
I’ve seen timeouts happen before.  Might need to have a retry mechanism added.

**Comment by pjaudiomv** [comment]
cool i think the sms problem may be isolated to the new england server, i just updated my charleston server to the same exact version and it still works and the new england one doesnt.

**Comment by radius314** [comment]
what was your search criteria for New England SMS lookup?

**Comment by pjaudiomv** [comment]
i tried multiple different searches but primarily edgartown, ma or 02539, and if i run that query after 7pm depending on day it will come up with nothing i tried multiple different servers as well as bmlt servers too. its weird though cause my south carolina one works properly on crna.orgs bmlt server

**Comment by radius314** [comment]
A change for this has been pushed to `master`.  You can give it a spin.

**Comment by pjaudiomv** [comment]
this is working great now, thanks.
