### ISSUE TITLE
voice or txt

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#23]
the new england region wants to be able to have a prompt to select weather you want listings by voice or txt, reason being is some people may still pay by txt on their phone i guess. has this issue come up with discussions in your region what were the results of it. if it is a deal breaker for them is this something i could add in between the address lookup and meeting search or something

**Comment by radius314** [comment]
It hasn’t come up, but I can make it a configuration value to ask at the end if you wanted them texted to you.

**Comment by radius314** [comment]
Just pushed a change to `master`.  If you pull the latest, and then add in your `config.php` the following you make SMS on voice calls optional.

```php
$sms_ask = true;
```

Please test and let me know how it works for you.

**Comment by pjaudiomv** [comment]
this works great now, thanks. only thing now this makes the sms gateway not work anymore. so i cant just txt the twilio number and get a result. not sure if theres anyway around that.

**Comment by radius314** [comment]
checking, it should work

**Comment by radius314** [comment]
Yeah looks like it's a bug, I just pushed a fix for it.  Please test it.

**Comment by pjaudiomv** [comment]
cool that fixed work great, one thing i noticed in testing which def wouldnt be from this push. when searching upcoming meetings im getting results for today and not tomorrow, it almost seems like its todays results in reverse order but not quite. if i do a search for boston for today i get ... some meeting boston 5:00pm as last result and if i do a search for upcoming that result turns up first now. i also did a today/upcoming search for the vineyard and similar thing happened with no results for monday showing up, only sunday

**Comment by radius314** [comment]
ok closing this moving the discussion to #25
