### ISSUE TITLE
possible sorting issue

### ISSUE THREAD

**Issue by radius314** [radius314/yap#25]
one thing i noticed in testing which def wouldnt be from this push. when searching upcoming meetings im getting results for today and not tomorrow, it almost seems like its todays results in reverse order but not quite. if i do a search for boston for today i get ... some meeting boston 5:00pm as last result and if i do a search for upcoming that result turns up first now. i also did a today/upcoming search for the vineyard and similar thing happened with no results for monday showing up, only sunday

**Comment by radius314** [comment]
requested by @pjaudiomv

**Comment by pjaudiomv** [comment]
besides that though the sorting is better than it was from a couple updates ago, its been giving me results closest geographically first not in time

**Comment by radius314** [comment]
Can you provide more details about what options you are using when you dial in?  Are you looking for meetings today near you, or looking for meetings upcoming?

Btw, it's not going to show any results for tomorrow if there are at least 1 result for today.

**Comment by pjaudiomv** [comment]
and using edgartown, ma or 02539, as asearch query there are 2 meetings that are found for today, but if i hit meetings upcoming shouldnt it give me tomorrows results, or how does that work

**Comment by radius314** [comment]
As of this moment upcoming is just today, and then if nothing left, it shows tomorrow.  This could be fixed potentially do what you are saying.

**Comment by radius314** [comment]
My upcoming search is getting this response

```xml
<Response>
<Say voice="woman" language="en">
Meeting information found, listing the top 5 results.
</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Result number 1</Say>
<Say voice="woman" language="en">Faith In Recovery Group</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Starts at Sunday 5:00 PM</Say>
<Pause length="1"/>
<Say voice="woman" language="en">500 Hope Street in Providence, RI</Say>
<Sms>
Faith In Recovery Group Sunday 5:00 PM 500 Hope Street in Providence, RI
</Sms>
<Pause length="1"/>
<Say voice="woman" language="en">Result number 2</Say>
<Say voice="woman" language="en">Fight Is Over</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Starts at Sunday 5:30 PM</Say>
<Pause length="1"/>
<Say voice="woman" language="en">270 Gifford Street in Falmouth, MA</Say>
<Sms>
Fight Is Over Sunday 5:30 PM 270 Gifford Street in Falmouth, MA
</Sms>
<Pause length="1"/>
<Say voice="woman" language="en">Result number 3</Say>
<Say voice="woman" language="en">Literary Ladies</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Starts at Sunday 5:30 PM</Say>
<Pause length="1"/>
<Say voice="woman" language="en">101 Page Street in New Bedford, MA</Say>
<Sms>
Literary Ladies Sunday 5:30 PM 101 Page Street in New Bedford, MA
</Sms>
<Pause length="1"/>
<Say voice="woman" language="en">Result number 4</Say>
<Say voice="woman" language="en">No matter what group</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Starts at Sunday 6:30 PM</Say>
<Pause length="1"/>
<Say voice="woman" language="en">320 Main Street in Hyannis, MA</Say>
<Sms>
No matter what group Sunday 6:30 PM 320 Main Street in Hyannis, MA
</Sms>
<Pause length="1"/>
<Say voice="woman" language="en">Result number 5</Say>
<Say voice="woman" language="en">Love Group</Say>
<Pause length="1"/>
<Say voice="woman" language="en">Starts at Sunday 6:30 PM</Say>
<Pause length="1"/>
<Say voice="woman" language="en">100 GReen Street in Fall River, MA</Say>
<Sms>
Love Group Sunday 6:30 PM 100 GReen Street in Fall River, MA
</Sms>
<Say voice="woman" language="en">Thank you for calling, goodbye.</Say>
</Response>
```

**Comment by pjaudiomv** [comment]
gotcha so whats the difference between today, and upcoming. today just gives you 5 closest in locationa nd time, and upcoming gives your 5 more later on or?

**Comment by radius314** [comment]
today near you, is the closest to your distance wise regardless of time

upcoming, is the next meetings within the BMLT radius search of the 20 closest meetings today

**Comment by radius314** [comment]
Right now the max results is always `5`.  Non-configurable at the moment.

**Comment by pjaudiomv** [comment]
gotcha ok that makes sense, i tightened up my search radius so thats why your results were different. the new england region wanted results for today and tomorrow but it def makes more sense the way that works. maybe ill put the radius back and tell the phoneline committee thats how it works. if your specifically searching for tomorrrow next there gonna want specific day searches, but i think the idea of this is to be quick and simple wwith out a million menu options. it would be cool to make the results confiugurable, i have to alter my script every time you make an update. as i wanted the configuration to have those things for future trusted servants to alter if need be without going into the code. $results_count = $GLOBALS['result_count_number']; is all i did. guess we can close this one now that i know how it operates.

**Comment by radius314** [comment]
Btw, I cannot support customizations you are making beyond the normal code base.  If you are making changes, it makes it very difficult to reproduce on my end.  You should send a pull request to be included into the main code base.

**Comment by radius314** [comment]
I will open a ticket for configuring the results count.

**Comment by pjaudiomv** [comment]
gotcha sorry about that, will keep main code base from now on and make pull requests. im gonna put my radius back too and then i think theres only one other change i make and ill put a request in for that,
