### ISSUE TITLE
SearchType 2 should try to fill the entire max results slots.

### ISSUE THREAD

**Issue by radius314** [radius314/yap#28]
Right now the "search for upcoming meetings" only looks at meetings today.  But if you are wanting to fill all the slots (say 5), and less than 5 come back, fill the rest with stuff from tomorrow.

cc: @pjaudiomv

**Comment by radius314** [comment]
change has been pushed

**Comment by pjaudiomv** [comment]
This seems to be working too, only request which may be kind of knit picking, but if there are results for tomorrow I'm getting all results by closest to me, which is good but I could get the following.
Result A Saturday
Result B Sunday
Result C Saturday
Result D Saturday

Would be nice to have all of current days listed first and if there are results for following day list those last

**Comment by radius314** [comment]
Ok it is intended to work the way you are saying.  Can you share your inputs into yap?  What was the search criteria and what option did you select?

**Comment by pjaudiomv** [comment]
i was using the sms gateway and the crna.org/main_server for bmlt, as well as the most current version as of a couple days ago with no mods on my part. input criteria was zip 29486 
this is when i tried on a monday night just before 7pm

![image2](https://user-images.githubusercontent.com/34245618/36937993-635b81aa-1ee9-11e8-8a1d-fa3465342683.png)

and thursday night a little after 7:30

![image1](https://user-images.githubusercontent.com/34245618/36938011-85549ed6-1ee9-11e8-9737-e32bd7686e18.png)

**Comment by pjaudiomv** [comment]
yap number 843-212-1328 and url  http://www.mvana.org/sca/chsyapnew/sms-gateway.php
http://www.mvana.org/sca/chsyapnew/input-method.php?Digits=2&PlayTitle=1

**Comment by radius314** [comment]
Ok I see the query issued: http://www.mvana.org/sca/chsyapnew/meeting-search.php?SearchType=1&Latitude=33.0843712&Longitude=-80.110762

**Comment by pjaudiomv** [comment]
yes thats it

**Comment by radius314** [comment]
are you sure you are on the latest version?

**Comment by pjaudiomv** [comment]
all good here, not right versions, i upgraded 2 instances of yap and not my 3rd, i have now deleted the 3rd as was not needed so no only have to manage, one for new england and one for carolina. sorry and thanks for being so patient with me.

**Comment by radius314** [comment]
No worries, glad it worked out.
