### ISSUE TITLE
music on hold (moh) for dial out

### ISSUE THREAD

**Issue by radius314** [radius314/yap#33]
currently when waiting for a call to connect using "yap" mode on the helpline section, you get dead air.  the point of this would be able to use a stock MOH mp3 for playback.

**Comment by pjaudiomv** [comment]
ive thought about this alot and i don't think stock is the way to go, I think it should be bill withers lovely day. haha. ive noticed even on grasshopper systems people would be more likely to wait a minute on hold with music than just ringing or silence for that matter.

**Comment by radius314** [comment]
it would be a stock file from Creative Commons (whatever we don't have to pay royalties on / get permission on), and then provide an option for anyone to swap in their own.

**Comment by pjaudiomv** [comment]
Makes sense

**Comment by radius314** [comment]
The way that I would have to implement this is less than ideal, but it's do-able for sure.

**Comment by radius314** [comment]
this is implemented in the unstable branch and destined for yap v2.  note that generally this is broken and will only dial the first volunteer.  some more work needs to be done to call this feature complete.  also need to add configuration value for MOH.

**Comment by radius314** [comment]
custom moh implemented in unstable

**Comment by pjaudiomv** [comment]
I tested this with a mp3 on my server and worked great.
