### ISSUE TITLE
helpline

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#37]
my helpline keeps dialing 0000000, but in my php log i can see its searching and finding volunteers not sure whats going on there

PHP Log
[11-Mar-2018 13:23:25 CST6CDT] https://www.charlestonna.org/main_server/client_interface/json/?switcher=GetFormats
[11-Mar-2018 13:23:25 CST6CDT] https://www.charlestonna.org/main_server/client_interface/json/?switcher=GetSearchResults&services=1&formats=52&advanced_published=0
[11-Mar-2018 13:23:25 CST6CDT] https://maps.googleapis.com/maps/api/timezone/json?keyAIzaSyCTDVPsTaa1vwieqh1cCR-LfQSHkq01-Ro&location=33.06002,-80.1049492&timestamp=1520792605

Twilio error code 13224 warn invalid phone number

<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial method="GET"
              callerId="+18432121328"
              action="helpline-dialer.php?service_body_id=1&amp;tracker=30&amp;Called=%2B18432121328">
        <Number>
                000000000            </Number>
    </Dial>
</Response>

**Comment by radius314** [comment]
investigating

**Comment by radius314** [comment]
Can you email me your config.php?

**Comment by pjaudiomv** [comment]
i just tried the new england region helpline and its doing the same thing, but used to work in a previous version

**Comment by radius314** [comment]
This is related to a time rendering issue with the BMLT with "Midnight" related times.

**Comment by radius314** [comment]
Will try to make a workaround.

**Comment by radius314** [comment]
Temporarily you can set the start time to 12:05 AM.

**Comment by pjaudiomv** [comment]
cool thanks that worked

**Comment by radius314** [comment]
I will try to patch this so that it bypasses the bug.

**Comment by radius314** [comment]
Btw, this is not really a bug.  It's an opinionated decision of the BMLT, because when folks are trying to indicate a midnight meeting, they typically include the "day before".  The BMLT then forces midnight responses to be "23:59".

**Comment by radius314** [comment]
cc: @littlegreenviper

**Comment by pjaudiomv** [comment]
gotcha makes sense

**Comment by LittleGreenViper** [comment]
This is weird. The 20Km should work fine, but I see it hanging.

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

However, directly to the NA Ireland server works:

https://bmlt.nasouth.ie/main_server/client_interface/json/?switcher=GetSearchResults&geo_width_km=20&long_val=-9.030&lat_val=51.578&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats

**Comment by radius314** [comment]
This was how I discovered this issue.  I just looked at your schedule and saw no one was on for Sunday.  https://www.charlestonna.org/yap/schedule.html.

**Comment by LittleGreenViper** [comment]
Should be patched in the latest checkin.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by LittleGreenViper** [comment]
Cool stuff, BTW. Yap is a game-changer.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by pjaudiomv** [comment]
if two different helpline volunteers are registered at the same time and the first doesn't pickup does it go to the next, or do we need to set like a 20sec timeout or something to then transfer

**Comment by radius314** [comment]
It should go to the next person if they hang up.  It may not time out though.  Can you open another issue to track this?

**Comment by radius314** [comment]
pushed to master

**Comment by radius314** [comment]
@pjaudiomv you should be able to set these to Midnight now.

**Comment by pjaudiomv** [comment]
cool works fine, thanks
