### ISSUE TITLE
Facebook messenger response has "in ," at the end of each line

### ISSUE THREAD

**Issue by paulnagle** [radius314/yap#39]
This is an example response that I get from Facebook Messenger when querying a county in Ireland:

```
Steps To Living Group Wednesday 8:30 PM Resource Centre, Navan, Co. Meath in ,
```

Is is possible to not get the "in ," at the end of each response? Addresses are formatted differently in Ireland, so not all fields will be populated in the out BMLT.

**Comment by pjaudiomv** [comment]
Is Navan entered into the city field or only street address field

**Comment by paulnagle** [comment]
Only street address

**Comment by paulnagle** [comment]
I've been trying out the YAP server with a Twilio number. I did a voice search for "Dublin" and it seems that occasionally the "in ," is being voiced as "Indiana". There is a Dublin in Indiana as well, not sure if it's co-incidental or not.

**Comment by radius314** [comment]
Yeah that's just the voice engine.  Once this is patched up that should go away.

**Comment by radius314** [comment]
@paulnagle this has been patched, please verify.

**Comment by paulnagle** [comment]
Verified as working correctly.
