### ISSUE TITLE
order of found meetings

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#4]
it may only be a thing since my bmlt isnt fully populated, but i noticed when i do a meeting search either by city or zip the 5th meeting that is listed is the closest one it would be nice if it was listed first and the one farthest away listed 5th (last).

**Comment by pjaudiomv** [comment]
/nerna/bmlt/main_server/client_interface/json/?switcher=GetSearchResults&sort_keys=distance_in_miles&long_val=-70.5502916&lat_val=41.363871&geo_width=-10&weekdays[]=3

**Comment by radius314** [comment]
what's the server url?

**Comment by pjaudiomv** [comment]
http://www.mvana.org/nerna/bmlt/main_server/

**Comment by pjaudiomv** [comment]
it must be the way bmlt handles search results, those coordinates are dead center on martha's vineyard, and tisbury, edgartown etc should definitley show up before falmouth or boston for that matter.

**Comment by pjaudiomv** [comment]
the actuall nearest locations are showing up, its just you would thnk the nearest one would be first

**Comment by radius314** [comment]
Nearest for that day?

**Comment by pjaudiomv** [comment]
yes nearest for that day, from the yap results on the phone and the txts boston shows up first and it should be last

**Comment by radius314** [comment]
It seems like an issue with the BMLT.

**Comment by pjaudiomv** [comment]
yes it is, i did a search using the bmlt on the web interface and same thing, the first two show up arent the closest but are the earliest ones so that makes since (7:30am) but the next 4 are at 7:00pm and that order isnt nearest first. i wonder how the bmlt decides to display the order of meetings in a general area if at same time, because its not nearest first. it didnt seem to be by when it was entered or first registered as service body or alphabetical either

**Comment by radius314** [comment]
It does appear to be an issue with the BMLT and will be addressed in a
future version.  However, I have a workaround that the maintainer gave me.
I'll implement this, later on, tonight and push out an update.

**Comment by pjaudiomv** [comment]
awesome, thanks again for your service.

**Comment by radius314** [comment]
The bug appears to be fixed.  Pull the latest version https://github.com/radius314/yap/commit/937f12083bdf0bd4572722d261ac887056bc03a1

**Comment by radius314** [comment]
> it may only be a thing since my bmlt isnt fully populated, but i noticed when i do a meeting search either by city or zip the 5th meeting that is listed is the closest one it would be nice if it was listed first and the one farthest away listed 5th (last).

what a long strange trip it's been.

**Comment by pjaudiomv** [comment]
Sure has, almost two years ago since I first got my hands on the bmlt. I've learned a lot in passed year, glad to be able to give some of that knowledge away.

**Comment by dgershman** [comment]
@pjaudiomv congrats!
