### ISSUE TITLE
Helpline volunteer sequential dialing

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#40]
if two different helpline volunteers are registered at the same time and the first doesn't pickup does it go to the next, or do we need to set like a 20sec timeout or something to then transfer

**Comment by pjaudiomv** [comment]
currently if i call, it just goes to the first persons number voicemail and doesn't go to the next number

**Comment by pjaudiomv** [comment]
https://www.charlestonna.org/yap/schedule.html
http://www.charlestonna.org/yap/helpline-dialer.php?service_body_id=1

in my twilio i get this

<?xml version="1.0" encoding="UTF-8"?>
<Response>
        <Dial method="GET"
              callerId="+18432121328"
              action="helpline-dialer.php?service_body_id=1&amp;tracker=0&amp;Called=%2B18432121328">
            <Number>
                843-900-7109            </Number>
        </Dial>
</Response>

and then ends with

<?xml version="1.0" encoding="UTF-8"?>
<Response>
<Hangup /></Response>

**Comment by pjaudiomv** [comment]
would it make sense to use Answering Machine Detection or Human Detection

**Comment by radius314** [comment]
AMD is beta with Twilio right now.  Not tightly integrated into their platform.  For now adding the timeout as a controllable parameter which defaults to 20 seconds.

**Comment by radius314** [comment]
https://www.twilio.com/docs/api/voice/answering-machine-detection

**Comment by radius314** [comment]
patched in https://github.com/radius314/yap/commit/8c51d8357e7dbea18f896fe64edf9cedcb863cd3, please test

**Comment by pjaudiomv** [comment]
weird it just tried the same number 4 times in a row till i hung up

**Comment by radius314** [comment]
which service body?

**Comment by pjaudiomv** [comment]
that was service body 2, maybe i entered wrong zip but called back and got service body 1, and was getting my voicemail. i lowered the time out a bit and now it seems to be working. it calls first number, then second number (in which case this is the last number) it then continues to dial the 2nd number till i hang up.

**Comment by radius314** [comment]
You may have also called between 12:00 AM and 12:05 AM.  If you remember there is a bug in the BMLT that required us to set this.

**Comment by radius314** [comment]
Until we patch #37, we are forced to this setting.

**Comment by pjaudiomv** [comment]
cool, aded a 3rd number and still working fine thanks.

**Comment by radius314** [comment]
i appreciate the extra testing effort for sure.
