### ISSUE TITLE
feature to set radius in miles on how far from location it looks for meetings

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#5]
note radius not diameter

**Comment by radius314** [comment]
Can you give an example of one query where you feel it should search further out?

**Comment by pjaudiomv** [comment]
This was a feature that was really specific to the vineyard as its an island and you have to take a ferry to get on or off it, if you called in the morning the first five results would be meetings off the island and an islander wouldnt get a result on the island. i tailored their yap alot to only display their meetings on a the local hotline. we can close this feature request

**Comment by radius314** [comment]
Interested to see what customizations you made.  This could be a useful thing if it comes up in the future for another location.

**Comment by pjaudiomv** [comment]
initially i just lowered the radius alot, but we have our own local hotline grasshopper number and we only have 7 meetings a week so i wanted it to just list all the meetings (7 of them) starting with the current day. i set the bmlt endpoint to only search our local area. this is awesome so now anytime someone changes meeting information its always updated. you can check it out 1-866-MVNA-NOW (866-686-2669). i just set extension 2 to forward to our twilio number. dont hit extension 1 as it cycles through 10 different addicts starting with bill h whos probably sleeping haha


[mvyap.php.zip](https://github.com/radius314/yap/files/1701661/mvyap.php.zip)

**Comment by radius314** [comment]
This is interesting.  Seems like a use-case for a small area versus a larger geographical area.  Let me see about building a separate page for this based on your idea.

**Comment by radius314** [comment]
Opened #11 to track this work.
