### ISSUE TITLE
Hints as config item

### ISSUE THREAD

**Issue by paulnagle** [radius314/yap#50]
Could we have the "hints" option for the Gather in city-or-county-voice-input.php set as a configuration item in config.php?  Twilio voice recognition is a having a hard time keeping up with Irish city and county name pronunciations.

https://www.twilio.com/docs/api/twiml/gather#attributes-hints

**Comment by radius314** [comment]
Probably makes sense to have the option to set gather language.

**Comment by paulnagle** [comment]
Yes, setting the gather language would probably help too

**Comment by radius314** [comment]
This has been implemented.  You can configure it by using the following section of the documentation.  https://github.com/radius314/yap#voice-recognition-optimizations
