### ISSUE TITLE
Custom "Greetings" recordings

### ISSUE THREAD

**Issue by tempsaint** [radius314/yap#62]
I'd like the ability to add a human recorded "greeting" to what callers hear when first connected to Yap. I realize that what's recited could be customized by changing the text in the configuration, but I think it would be nice for callers to hear a human voice to select how to search, or for additional info (like telling people to check a website for other info).

**Comment by radius314** [comment]
It's possible now to override the text in the configuration as of Yap 1.1.0.  

https://github.com/radius314/yap#language-options

Human voices would be further down the road.

**Comment by radius314** [comment]
This has been implemented in the latest `unstable`, and will be released with Yap 2.0
