### ISSUE TITLE
helpline to helpline redirects for internal yap calls

### ISSUE THREAD

**Issue by radius314** [radius314/yap#66]
@pjaudiomv asked for this feature:

"When using Volunteer Dialer, I have two areas that overlap somewhat geographically and we have a unified meeting schedule and they now wish to have a unified phone number. all my helpline volunteers are stored under one area (and they dont care what volunteer from waht area answers a call). for the 2nd area would i then need to renter all the same helpline volunteers and set the phone number to yap. or if I dont set a number in the bmlt for the 2nd area will it automatically use the 1st area since its the closest one with a phone number, or do i need to still set the 2nd one to yap and then not enter any volunteers.  hope this wasnt too confusing"

**Comment by radius314** [comment]
@pjaudiomv just pushed an enhancement to the master branch.

essentially you can put `yap->x`, where `x` is the service body id you want to redirect to.

`schedule.html` will also show the appropriate schedule and indicate that it is redirected in the dropdown.

**Comment by pjaudiomv** [comment]
this worked great
