### ISSUE TITLE
area helpline search

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#67]
#11
It would be nice for an small area use case with helplines to have a function to be able to skip search by city or zip, so that it can dial and go directly to the helpline number or volunteers. I started working on this feature for martha's vineyard helpline but it would be nice to have this built in to the base code.

**Comment by radius314** [comment]
Are you wanting a direct dial to helpline volunteers?  Or looking for something different?

**Comment by pjaudiomv** [comment]
yes direct dial to helpline volunteers

**Comment by radius314** [comment]
does this mean skipping the meeting finding option going right to dialing volunteers?  or does this mean on option press 1, then skip the location gathering menu?

**Comment by pjaudiomv** [comment]
On option one skip location gathering, option two meeting finder will still do location gathering

**Comment by radius314** [comment]
Skipping location gathering is trivial, set the web hook url following a similar convention as below:

https://archsearch.org/yap/helpline-search.php?Digits=Newark%2C+NJ

**Comment by pjaudiomv** [comment]
Where would I set that in the index.php file

**Comment by radius314** [comment]
You said, skipping meeting information lookup, so this would replace index.php in your webhook configuration.  This would be for a direct dial to helpline volunteers.

**Comment by radius314** [comment]
I misunderstood your comment above.  This is for making a direct dial helpline without meeting finding.

**Comment by pjaudiomv** [comment]
Sorry I want it to do meeting finding with location lookup, but if you do helpline to not do location lookup and direct dial them

**Comment by pjaudiomv** [comment]
what if we did something like this on input-method.php and add a static variable of maybe $helpline_direct_location = "City, State"

    if (isset($GLOBALS['helpline_direct_location']) && $GLOBALS['helpline_direct_location']) {
      header("Location: helpline-search.php?Digits=$GLOBALS['helpline_direct_location']");
      exit();
    }
    else if ($searchType == "1") {
        $searchDescription = word('someone_to_talk_to');
    } else if ($searchType == "2") {
        $searchDescription = word('meetings');
    } else {
        header('Location: fetch-jft.php');
        exit();
    }

**Comment by pjaudiomv** [comment]
wow that was silly where i put it before

    if ($searchType == "1") {
      if (isset($GLOBALS['helpline_direct_location']) && $GLOBALS['helpline_direct_location']) {
        header("Location: helpline-search.php?Digits=" .$GLOBALS['helpline_direct_location']);
        exit();
      }
        $searchDescription = word('someone_to_talk_to');
    } else if ($searchType == "2") {
        $searchDescription = word('meetings');
    } else {
        header('Location: fetch-jft.php');
        exit();
    }

**Comment by radius314** [comment]
what file is this in?

**Comment by pjaudiomv** [comment]
sorry its still in input-method.php, i tested it 3 different ways and works.
1. by with the config option enabled and hitting 1, which directly redirects to callers as intended.
2. with the config option disabled and it gos to location gathering for helpline as it should normally.
3. hitting option 2 to find a meeting gos to location gathering for finding a meeting.

**Comment by radius314** [comment]
ok it makes sense now.  go ahead with your pr.

**Comment by pjaudiomv** [comment]
damn im not sure how to do that without messing things up since i just created that readme pull request.

**Comment by radius314** [comment]
I merged it, but in the future, you can just have different branches for features.

**Comment by radius314** [comment]
And then you can have multiple PRs per feature.

**Comment by pjaudiomv** [comment]
gotcha

**Comment by radius314** [comment]
Let me know how your test goes.

**Comment by pjaudiomv** [comment]
Testing went fine I tested it every way possible which with the $helpline_config_location config option both enabled and disabled. (This ended up being 4 different ways) I also tested with a couple different locations in the two different service bodies I'm using and it always returned to my primary service body using the helpline redirect option

**Comment by pjaudiomv** [comment]
Call redirects went in correct order too, I forgot that the different days hadn't been implemented yet so I moved some numbers around and this works great now. It's live and I our unified helpline number is being forwarded from callexperts.com to yap

**Comment by radius314** [comment]
You can implement different days.  You would need to make an entry for each day.

**Comment by pjaudiomv** [comment]
gotcha the schedule.html just doesnt reflect this properly?

**Comment by radius314** [comment]
it should.  as long as the name matches

**Comment by pjaudiomv** [comment]
hmm no matter what day i put them on they all show up on everyday

**Comment by radius314** [comment]
Which root server / service body/

**Comment by pjaudiomv** [comment]
crna.org/main_server/ service body 19 same config as i sent to your email the other day

**Comment by radius314** [comment]
sorry, I can't keep up, I'm debugging lots of Yap servers every day.

**Comment by radius314** [comment]
what is service body 19?

**Comment by pjaudiomv** [comment]
south coastal area

**Comment by pjaudiomv** [comment]
no rush either, It would be nice to figure out at some point though. and if its just my crappy server or settings or an issue with base code

**Comment by pjaudiomv** [comment]
ahh ok what if i dont want them on a day, should i just set the time to a small intervel? also one other weird think is the times are all changing by 15min intervels idk if this has to do with the grace period. but if i set the time for 12:00 it shows up on schedulehtml as 12:15, 7:00 shows up as 7:15 etc.
http://www.crna.org/yapscripts/southcoastal/schedule.html

**Comment by radius314** [comment]
If you only want them on one or more specific days.  I will provide no further support on this feature as it's a major distraction from future versions.

**Comment by pjaudiomv** [comment]
alright cool makes sense.

**Comment by pjaudiomv** [comment]
thanks again.

**Comment by radius314** [comment]
It doesn’t make sense to add more functionality to a feature that is being
replaced with something more robust.

**Comment by pjaudiomv** [comment]
ya I totally agree, it works fine as for what my local service bodies need anyway.

**Comment by radius314** [comment]
this is implemented now... use `override_service_body_id=x` on your webhook.
