### ISSUE TITLE
Add foreign language support

### ISSUE THREAD

**Issue by sfrna** [radius314/yap#72]
Would like to see support in order of importance as follows: Spanish, Brazilian-Portuguese, and Russian. If we can find someone to translate we will also be interested in Haitian Creole as well.

While we are kicking this around is the voice recognition system robust enough to identify what language is being spoken or will it be a sub-menu selection?

**Comment by radius314** [comment]
I have already start some work on a new sub menu that would support such a feature.

**Comment by sfrna** [comment]
What do we need to translate in the voice prompts? Will Twilio recognize people speaking in Spanish if the config file has a US-EN configuration?

**Comment by radius314** [comment]
This is on hold right now.  Working on other features.

**Comment by sfrna** [comment]
That's fine. It seems the standard computer voice prompts would need to be translated, correct? might as well do it now so when you have time we can move forward quickly.

**Comment by radius314** [comment]
Cannot provide guidance at this point as it's a moving target.

**Comment by radius314** [comment]
This has been delivered in the latest `unstable`.  It's lacking some functionality, but the guts are there.

**Comment by webfacilitator** [comment]
[https://drive.google.com/file/d/1fVWmUxkaqEg_tsiS2nxlO1L6VS94Q5uk/view?usp=sharing](url)

**Comment by webfacilitator** [comment]
We have a sp-US file with Spanish prompts that can be used.
