### ISSUE TITLE
Take JFT out of stealth mode

### ISSUE THREAD

**Issue by sfrna** [radius314/yap#73]
Is it possible to have this added as an option in the config file? That way those who want it can have it and those who don't, won't.

**Comment by sfrna** [comment]
If someone will tell me what files I need to look at I will see if I can learn.

**Comment by radius314** [comment]
this will be released as part of Yap 1.3.0

**Comment by radius314** [comment]
PR merged to `master` please test.

**Comment by pjaudiomv** [comment]
just tested this and works as expected

**Comment by sfrna** [comment]
Please add this to the readme file: static $jft_option = 'true';

**Comment by pjaudiomv** [comment]
It's there 3rd section from very bottom I believe
