### ISSUE TITLE
Pass Incoming Caller ID through to Helpline Volunteer via SMS

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#74]
This would help with volunteers having a call back number in case a call was dropped while talking with an inbound caller

**Comment by pjaudiomv** [comment]
This is how it was setup originally but then there were issues of the volunteers not picking up the phone because they didn't know the number. I'm sure this could become an option again with a setting.

**Comment by californiasteve** [comment]
I can see that, I wonder if there's a way to pass inbound caller ID through to volunteer before a call connects to the inbound caller?

**Comment by pjaudiomv** [comment]
Like a txt of there number? That could be cool

**Comment by californiasteve** [comment]
I didn't think of that but that would work.

**Comment by radius314** [comment]
I'm a bit lost on this.  Currently today the functionality is that the "Called Number" (your helpline number), is the number displayed to the volunteer.

**Comment by pjaudiomv** [comment]
Yes Steve was wondering if somehow the callers (addict looking for help) number can show up on caller ID for helpline volunteer, or have the callers number be txted to the helpline volunteer that picks up the call

**Comment by radius314** [comment]
How is that going to make the volunteer more likely to pick up the call?  The way it's set up today, you know that if you are getting a call from the same number it's a helpline call.  Part of helpline training should be programming this number into your phone and saving it as "Helpline Call" or something like that.

**Comment by pjaudiomv** [comment]
Yes it's not, that's where the txt idea came into play, so if the call got dropped the volunteer would have the number of the caller to be able to call them back

**Comment by pjaudiomv** [comment]
Cool

**Comment by californiasteve** [comment]
Thanks Danny

**Comment by sfrna** [comment]
I can understand why you might want this, but I thought we are an anonymous organization? If they want to call back they can.

**Comment by radius314** [comment]
The goal of this is to make it so they know "who" to call back.  Call records are available to anyone on most phone systems, so this is not a strange request.

**Comment by californiasteve** [comment]
A typical phone line would be someone calling a phone (cell or land) which shows the incoming call ID. I believe some service committees will want that same feel to this app as they may have set up now.

**Comment by radius314** [comment]
It would be an option so that the service body can decide what they feel is appropriate.

**Comment by radius314** [comment]
Delaying this feature until Yap 2.0 is completed.

**Comment by radius314** [comment]
This is available in the latest `unstable`, slated for beta2.

**Comment by pjaudiomv** [comment]
Tested this as well and works as expected, send txt with callers number when calling helpline portion only.
