### ISSUE TITLE
How to change JFT feed

### ISSUE THREAD

**Issue by sfrna** [radius314/yap#76]
We have some Areas here in South Florida that might want to use the Gray For Today feed in lieu of JFT. Where would we make changes?

**Comment by radius314** [comment]
https://github.com/radius314/yap/blob/master/fetch-jft.php#L7.

Keep in mind that I will not be accepting a pull request to change the JFT feed conditionally in the main code base.  I can also not support any customizations that you are making.

**Comment by sfrna** [comment]
No problem. It's an easy fix. I will just add it to the tutorial I'm working on. Other Areas might also want to do an non-NAWS, Inc JFT feed (an older one).
