### ISSUE TITLE
option to change outbound caller id

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#77]
this could be useful if forwarding an existing non twilio helpline number to twilio. my local area helpline number is owned by callexperts.com and is set to forward to twilio, the helpline volunteers see the twilio number when called, it would be nice if they could see the actual helpline number. we are in the process of buying the number and porting it to twilio but this process will take some time and apparently $$$$$. this number would obviously have to be a verified twilio number.

**Comment by radius314** [comment]
Porting a number to Twilio is free.

**Comment by radius314** [comment]
I'm actually porting a Grasshopper number over to Twilio as of last night.

**Comment by pjaudiomv** [comment]
yes but buying it to be able to port it from callexperts.com is not, they want $400 to release the number. still over the course of time we will still save lots

**Comment by radius314** [comment]
Wow.  That it's insane.  Just get rid of the old number.  Phase it out.

**Comment by pjaudiomv** [comment]
I know thats what I suggested but all the old timers are like we have had this number for 25 years...

**Comment by radius314** [comment]
My ASC is paying $24.95 a month for a year, swapping out schedules (and other places with the new number).

**Comment by pjaudiomv** [comment]
how do you initially get the letter of Authorization from twilio, I want to transfer martha;s vineyrd number which is grasshopper to twilio

**Comment by radius314** [comment]
Can we take this conversation to Slack?

**Comment by pjaudiomv** [comment]
I tested this and works as expected
