### ISSUE TITLE
Create an interface for direct access 

### ISSUE THREAD

**Issue by sfrna** [radius314/yap#80]
I would like for our telephone people to be able to have direct access (login and text editor) to make changes to the configuration file.

**Comment by radius314** [comment]
This is potentially destructive.  Can you be more specific?

**Comment by sfrna** [comment]
Like this. Where the phoneline chair can make changes to the config.php file. 

http://sfrna.net/machform/index.php

**Comment by radius314** [comment]
What settings would someone need to change?

**Comment by sfrna** [comment]
Config file settings for updates?

**Comment by radius314** [comment]
This would be very dangerous.  I’m not clear what the goal is here.  Only
server administrators should have access to configuring the core
functionality.  If there is some specific feature that would need to be
configured then I’d like to hear about it.  Otherwise, this will not be
implemented.

**Comment by pjaudiomv** [comment]
Fallback number seems like one the Phoneline chair may want to change as position gets rotated

**Comment by radius314** [comment]
This will be considered differently in Yap 2.0.  And it will not be
included in the config.php file.
