### ISSUE TITLE
Cannot disable volunteer routing

### ISSUE THREAD

**Issue by radius314** [radius314/yap#81]
**Describe the bug**
After enabling volunteer routing there is no way to disable it.

**To Reproduce**
1. Go to 'Services Bodies'
2. Click on 'Configure' next to any item.
3. Enable 'Volunteer Routing'
4. Click 'Save'
5. Reload the page.
6. Click 'Configure' next to the same item.
7. Uncheck 'Volunteer Routing;
8. Click 'Save'
9. Reload the page.
10. Click 'Configure' next to the same item.
11. Observe that the 'Volunteer Routing' item is still checked.

**Expected behavior**
You should be able to disable 'Volunteer Routing'

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Safari
 - Version: 11.1.1

**Comment by pjaudiomv** [comment]
same here
OS: MacOS Sierra
Browser: Firefox
Version: 61.0

**Comment by radius314** [comment]
It’s not OS specific.

**Comment by pjaudiomv** [comment]
this works for me now

**Comment by radius314** [comment]
It's definately not working, this wasn't fixed.

**Comment by pjaudiomv** [comment]
oh ok, it just looks like it is. before it wouldnt let me go back and uncheck the box, now it does. My B I know this is beta.

**Comment by radius314** [comment]
It's saving duplicate information, you may need to go into your BMLT and clear out extra `_YAP_CONFIG_` entries.

**Comment by radius314** [comment]
fixed / reworked in ced85d79265d2df83540d10100bad97fb6e74699

**Comment by pjaudiomv** [comment]
word just checked works great (also checked bmlt this time), and dropdown logic def makes sense
