### ISSUE TITLE
Adding/Removing Volunteers

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#85]
**Describe the bug**
When adding volunteers if you remove one and then add another one, the id order numbers are duplicate and the shift gets added to the volunteer above it. if you refresh the page or go to another and come back they show up properly.

**To Reproduce**
1. Add two volunteers.
2. Remove the first one.
3. Add another volunteer and add a shift. the shift shows up on the above volunteer. There ID numbers appear the same as well
4. if you refresh page, or go to another section and come back the shift shows up on the right volunteer, as well as having seperate id numbers.

**Expected behavior**
That the shift show up on the newly added volunteer with seperate id numbers, without having to refresh page.

**Screenshots**
![yapbeta2](https://user-images.githubusercontent.com/34245618/42332954-64d89cc4-8047-11e8-9fb5-f6d160c42ec9.png)
![yapbeta1](https://user-images.githubusercontent.com/34245618/42332953-64c45836-8047-11e8-8cdd-e8776769964b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser Safari
 - Version 11.0.1

**Additional context**

**Comment by radius314** [comment]
fixed in latest unstable

**Comment by pjaudiomv** [comment]
tested this and works fine now. thanks.
