### ISSUE TITLE
Error when clicking on Service Bodies Tab

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#87]
I get the error "Warning: Invalid argument supplied for foreach() in /home/eanaonli/public_html/bmlt/YAP2.0/functions.php on line 250" when clicking on the Service Bodies Tab.

**To Reproduce**
1. Click on Service Bodies Tab

**Expected behavior**
Show Service Bodies

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/42400926-fd4cbb74-8138-11e8-97a8-5b9af6b9ac95.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Build 10.0.16299
 - Browser Firefox
 - Version 60.0.2

**Comment by radius314** [comment]
are you running latest `unstable` or running `2.0.0-beta1`?

**Comment by californiasteve** [comment]
2.0.0-beta1

**Comment by californiasteve** [comment]
My bad, it's the unstable

**Comment by radius314** [comment]
That does not seem possible that you are on the latest `unstable`.  Line 250 is blank.

**Comment by californiasteve** [comment]
I'm reloading it in case there was error uploading.

**Comment by californiasteve** [comment]
Still getting error, can it be because I have zones setup. I have Western States and Southern setup then their regions/areas

**Comment by pjaudiomv** [comment]
hey steve, are you sure you have your bmlt server set properly in the config file, this isnt coming up with anything either which is in an Albuquerque, https://bmltserver.org/YAP2.0/meeting-search.php?Latitude=35.0734065&Longitude=-106.5760857

**Comment by pjaudiomv** [comment]
also if you have any redirects setup on that bmlt, yap may not like that

**Comment by californiasteve** [comment]
I had a redirect and took it off when I started using yap. There is something weird going on because it won't allow me to access ../main_server/ without adding index.php to it. Back to the Cpanel

**Comment by pjaudiomv** [comment]
once you get your bmlt squared away, yap should be fine.

**Comment by californiasteve** [comment]
Redirect is fixed still getting error.

**Comment by pjaudiomv** [comment]
do you have the semantic admin enabled on your bmlt server

**Comment by pjaudiomv** [comment]
actually that wouldnt be it, and you must if you can login to the admin

**Comment by radius314** [comment]
we should probably add a check to the `upgrade-advisor.php` to see if the semantic admin is enabled.

**Comment by radius314** [comment]
1) Semantic admin enablement is not related to being able to login.  
2) Can you email me your config.php?
3) Have you updated your instance to the latest `unstable`?

**Comment by californiasteve** [comment]
No, on the beta1 still

**Comment by radius314** [comment]
Ok your comment seemed confusing, your last one indicated `unstable.`

**Comment by californiasteve** [comment]
Correct, I checked it again it is beta1

**Comment by radius314** [comment]
Ok it seems to be be failing on pulling the service bodies that are permissible for the logged in user.  Can you email me your config.php?

**Comment by radius314** [comment]
I see the issue.  You have appended `index.php` to your root server entry.

`static $bmlt_root_server = "https://bmltserver.org/main_server/index.php";`

Change it to:

`static $bmlt_root_server = "https://bmltserver.org/main_server/";`

@pjaudiomv we should check for this in the upgrade-advisor.php.
