### ISSUE TITLE
No service bodies displayed under service bodies tab with new user

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#89]
**Describe the bug**
I created another person with BMLT service body admin rights. When I login under their credentials and click on the service bodies tab it doesn't show and service bodies. In the db I have them access to a region and their asc. When I click volunteers it shows all of the service bodies I have loaded in the db.

**What version are you running**
Latest Unstable

**To Reproduce**
1. Log in
2. Click on services bodies

**Expected behavior**
Should be able to view all of the service bodies the user has access to.

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/42413756-7de351fe-81ec-11e8-9978-feceef8087bb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 61.0 64bit

**Comment by radius314** [comment]
Can you email me your config.php?

**Comment by radius314** [comment]
I'm guessing it's the same config, if so, send me the credentials for this new user.

**Comment by radius314** [comment]
Can you also attach a screenshot to the ticket of how the user is set up in the BMLT?

**Comment by radius314** [comment]
Validating this now, I think it's a bug in the BMLT.

**Comment by californiasteve** [comment]
![image](https://user-images.githubusercontent.com/31661648/42414056-179612ae-81f3-11e8-80b6-954f8ad49ebf.png)

**Comment by radius314** [comment]
It's a bug with the BMLT, filed as https://github.com/LittleGreenViper/BMLT-Root-Server/issues/12.

I will be working around this issue, and will push a patch shortly.

**Comment by radius314** [comment]
pushed a patch to latest `unstable`

**Comment by radius314** [comment]
@californiasteve have you verified that this is working for you now?

**Comment by californiasteve** [comment]
I just tried it and not working.

**Comment by radius314** [comment]
did you update the software?

if not use this version https://github.com/radius314/yap/archive/83dfcae1a99f843cb27a0baaccb9e0c601d868ae.zip

**Comment by californiasteve** [comment]
Yes, went to beta2 a couple of hours ago, do you want me to install this version?

**Comment by radius314** [comment]
Yes, basically the patch for this came in after beta2 was cut.  This is essentially beta2 + the patch for this bug.

**Comment by californiasteve** [comment]
Uploading right now

**Comment by californiasteve** [comment]
Works fine, thanks.
