### ISSUE TITLE
sms gateway

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#9]
know you just did this last night and you may know about it, but ive been testing it and works great and super quick. I do get a warning in my twilio debugger.

Warning 12200
Invalid content was found starting with element 'Say'. One of '{Sms, Message, Redirect}' is expected
get: http://www.mvana.org/sca/chsyapnew/meeting-search.php

`<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Say voice="woman" language="en">Meeting information found, listing the top 5 results.</Say>
    <Sms>Hollywood Group of Hope Group
Monday 7:30 PM
114 Walker Ln. in Goose Creek, SC</Sms>
    <Sms>All Kidding Aside Group
Monday 7:00 PM
3250 Ladson Road in Ladson, SC</Sms>
    <Sms>Step Working Study Guide Group
Monday 6:00 PM
2010 Hawthorne Dr in North Charleston, SC</Sms>
    <Sms>Primary Purpose
Monday 9:00 AM
2010 Hawthorne Ave in North Charleston, SC</Sms>
    <Sms>Back to Basics
Monday 12:00 PM
2010 Hawthorne Ave. in Bldg in back in North Charleston, SC</Sms>
    <Say voice="woman" language="en">Thank you for calling, goodbye.</Say>
</Response>`

I temporary fixed this by creating a meating-searchsms.php and removing those say parts then directing my sms gateway to that, but I but you have some tricks up your sleave. maybe making those parts conditional to only voice calls

**Comment by radius314** [comment]
yeah this is a known issue, thanks for opening this.

**Comment by radius314** [comment]
fixed in https://github.com/radius314/yap/commit/96d2c3bb1d945302ec830a8f6eb1e7086223eaba?diff=split

**Comment by radius314** [comment]
please verify

**Comment by pjaudiomv** [comment]
awesome that fixed it, no warnings and works fine
