### ISSUE TITLE
Schedule dropdown shows all service bodies instead of ones admin has access to

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#90]
**Describe the bug**
When the admin logged in has access to only one service body they see all the service bodies that are active.

**What version are you running**
https://github.com/radius314/yap/archive/83dfcae1a99f843cb27a0baaccb9e0c601d868ae.zip

**To Reproduce**
1. Login with an admin who has only one service body they have access to. Click on schedules and see all services bodies that are enabled.

**Expected behavior**
Only see the service bodies they have access to

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/42485739-964477a4-83be-11e8-824d-ad708303657d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 61.0.1

**Comment by radius314** [comment]
good catch, patch was pushed to unstable.

**Comment by californiasteve** [comment]
Works as expected
