### ISSUE TITLE
Schedule not showing 24/7 shifts on Monday

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#91]
**Describe the bug**
On schedule page 24/7 shifts not showing on Monday/current day

**What version are you running**
Enter 

**To Reproduce**
Click on schedule

**Expected behavior**
Show 24/7 volunteers on every day of the week

**Screenshots**
![image](https://user-images.githubusercontent.com/31661648/42486453-d11949a6-83c1-11e8-83cc-2d545518641e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 61.0.1

**Comment by pjaudiomv** [comment]
I was having same issue

**Comment by radius314** [comment]
fix was pushed to latest `unstable`

**Comment by californiasteve** [comment]
Tested, looks good.
