### ISSUE TITLE
Upgrade Advisor and tooltip not displaying on Safari

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#93]
**Describe the bug**
When logging in to the admin on safari the upgrade advisor and tool tip do not display. this does display fine on firefox and chrome. 

**What version are you running**
latest unstable 7-13-2018

**To Reproduce**
1. Go to admin login
2. view home screen

**Expected behavior**
upgrade and tool tip display

**Screenshots**
![unstable](https://user-images.githubusercontent.com/34245618/42697162-5ff839fc-8688-11e8-83c5-3fb36096f422.png)

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser Safari
 - Version 11.0.1

**Additional context**
displays fine on firefox and chrome. 

Javascript Errors:

**Safari**
[Warning] jQuery.Deferred exception: Can't find variable: showUpgradeAdvisorResults (2) (jquery-3.3.1.min.js, line 2)
(anonymous function) — home.php:89
l — jquery-3.3.1.min.js:2:29381
(anonymous function) — jquery-3.3.1.min.js:2:29679
undefined

[Error] ReferenceError: Can't find variable: showUpgradeAdvisorResults
	(anonymous function) (jquery-3.3.1.min.js:2:31048)

[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (bootstrap.min.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (popper.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (bootstrap.min.js.map, line 0)

**This popped up on my firefox**
Source map error: request failed with status 404
Resource URL: http://bmlt.charlestonna.org/yap3/admin/js/bootstrap-4.1.0.min.js
Source Map URL: bootstrap.min.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://bmlt.charlestonna.org/yap3/admin/js/popper.min.js
Source Map URL: popper.min.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://bmlt.charlestonna.org/yap3/admin/css/bootstrap-4.1.0.min.css
Source Map URL: bootstrap.min.css.map[Learn More]

**Comment by radius314** [comment]
Can you include the errors in your JavaScript console?

**Comment by radius314** [comment]
This is an odd issue.

**Comment by pjaudiomv** [comment]
Yes, works fine on my phone and both my other browsers. I take it it works fine on your safari

**Comment by radius314** [comment]
Works good on Safari on Mojave Beta 3.

**Comment by pjaudiomv** [comment]
Gotcha hopefully it's an isolated incident then, maybe I'll try clearing my browser cache and doing a control refresh

**Comment by radius314** [comment]
The only thing I can think of is that that yap.js is not getting loaded by the time the jquery deferred happens.

It’s looks like it’s not even getting to the point of making the request to upgrade-advisor.php.

**Comment by radius314** [comment]
I guess the easy fix here is to change it to a server side request.

**Comment by pjaudiomv** [comment]
Gotcha

**Comment by radius314** [comment]
pushed to latest unstable

**Comment by radius314** [comment]
@pjaudiomv can you verify?

**Comment by pjaudiomv** [comment]
My bad meant to and forgot, yes this works fine now. Thanks.
