### ISSUE TITLE
yap install folder needs to be yap

### ISSUE THREAD

**Issue by gutterwall** [radius314/yap#94]
I named the yap folder Yap (I had that working in version 1.* branch) but found the conference bridge joining is hardcoded to be //yap/...   and got a 404.  If someone is trying it out and doesn't name it yap it fails.

**What version are you running**
2.* latest

**To Reproduce**
name folder something other than (domain)/yap
set up everything and try the volunteer hotline options
The caller gets an error message when trying to connect to the volunteer.

**Expected behavior**
caller connected to Volunteer

tested on ios and android

Msg | "An attempt to retrieve content from https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541 returned the HTTP status code 404"
-- | --
msg | "An attempt to retrieve content from https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541 returned the HTTP status code 404"
sourceComponent | "12000"
ErrorCode | "11200"
httpResponse | "404"
LogLevel | "ERROR"
url | "https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541"

Msg | "An attempt to retrieve content from https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541 returned the HTTP status code 404"
-- | --
msg | "An attempt to retrieve content from https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541 returned the HTTP status code 404"
sourceComponent | "12000"
ErrorCode | "11200"
httpResponse | "404"
LogLevel | "ERROR"
url | "https://metrorichna.org/yap//helpline-outdial-response.php?conference_name=2_2823109_1531446541"

**Comment by pjaudiomv** [comment]
By latest version do you mean the latest master, beta3 or the latest unstable

**Comment by gutterwall** [comment]
Beta

**Comment by gutterwall** [comment]
2.0 beta 3?

**Comment by pjaudiomv** [comment]
I'd be curious what your log files say wether you have a php log in that folder or server log. As well as your twilio log what errors you have. I don't believe the root folder is hard coded anywhere as most my instances are not named yap. And I have yap beta3 in a folder named yapbeta that works fine

**Comment by pjaudiomv** [comment]
Firstly what errors are you getting in twilio

**Comment by gutterwall** [comment]
Msg=Got+HTTP+404+response+to+https%3A%2F%2Fmetrorichna.org%2Fyap%2F%2Fhelpline-dialer.php%3Fservice_body_id%3D2%26tracker%3D1%26FriendlyName%3D2_2823109_1531446541&statusCallback=https%3A%2F%2Fmetrorichna.org%2Fyap%2F%2Fhelpline-dialer.php%3Fservice_body_id%3D2%26tracker%3D1%26FriendlyName%3D2_2823109_1531446541&ErrorCode=15003&LogLevel=WARN

**Comment by californiasteve** [comment]
My folder is YAP2.0 and I have no problems

**Comment by pjaudiomv** [comment]
Cool I can take a better look when I get home

**Comment by radius314** [comment]
`yap` is not hardcoded anywhere in the application for any paths.  you can name the virtual directory whatever you want to (mine is called yap-unstable). did you provision a new number with an update webhook to that new folder, or are you using the same number w/o and updated webhook?

**Comment by radius314** [comment]
it also works with any combinations of paths (and without any at all)

**Comment by radius314** [comment]
Can you send a screenshot of your webhook?

**Comment by radius314** [comment]
It looks like there was an error before the one you posted.

**Comment by radius314** [comment]
@gutterwall, thanks for adding those messages.  What was your webhook at the time of the error?

**Comment by gutterwall** [comment]
I did have lower case https://metrorichna.org/yap
So that might be the disconnect

**Comment by radius314** [comment]
Not sure how go you got a 404, those urls are good.

**Comment by gutterwall** [comment]
I changed my website to lowercase.  It was working for me uppercase too
though.

**Comment by radius314** [comment]
I’m  bit confused about the conditions that caused the error.  I’m trying
to repro on end.

**Comment by radius314** [comment]
I did notice some weirdness when you have a webhook configured without a final trailing `/` and not using `/index.php`.  I've added a check into the upgrade-advisor.php to ensure this doesn't happen.

**Comment by gutterwall** [comment]
As long as it is clear in the setup guides, please close it as good
enough.  Just figured easy rookie mistakes need to be documented

**Comment by radius314** [comment]
The upgrade advisor should pull on the coat tails now.  Thanks for opening this.
