### ISSUE TITLE
Volunteer accordian not allowing input on "Volunteers" tab on Android phone

### ISSUE THREAD

**Issue by californiasteve** [radius314/yap#97]
**Describe the bug**
On the Volunteers tab, I can move the accordion with the single volunteer but cannot click on the + sign or input text to edit volunteer.

**What version are you running**
yap 2.0 beta4

**To Reproduce**
On an android phone login, select Volunteers tab, select service body, try to click in name text box to edit or click on + to open or click on checkbox. All other buttons work fine on the page

**Expected behavior**
When clicking in textbox it allows editing and clicking on + allows accordion to expand

**Smartphone (please complete the following information):**
 - Device: Samsung S7 Active
 - OS: Android 8.0.0
 - Browser Chrome 67.0.3396.87

**Comment by radius314** [comment]
@pjaudiomv are you able to repro on your android device?

**Comment by pjaudiomv** [comment]
Not on android but iOS 11.3 iPhone 6s can't input into txt boxes for volunteers or phone numbers, editing shifts is impossible for some as when I scroll down it moves the whole volunteer box like I'm trying to rearrange it. Maybe only making the top portion of the volunteer box draggable could fix that. I'm also working on latest unstable not beta 4

**Comment by radius314** [comment]
Yeah probably need to change the item that performs the drag.  The real estate is taken over completely.

**Comment by pjaudiomv** [comment]
Yes if I scroll screen to the very very far left or right I can do it fine so yes less real estate

**Comment by radius314** [comment]
Can you try the latest commit 705130f7 in unstable.

**Comment by pjaudiomv** [comment]
so much more manageable, this works fine now

**Comment by radius314** [comment]
still unable to edit the fields?

**Comment by pjaudiomv** [comment]
no actually, that works now too

**Comment by pjaudiomv** [comment]
which is weird, I don't understand it but ill take it

**Comment by radius314** [comment]
@californiasteve can you retry with the latest unstable?

**Comment by californiasteve** [comment]
Scrolling is easier but still cannot edit or click on accordions.

**Comment by californiasteve** [comment]
Now it's working fine. I rebooted my phone. may have been stuck in cache.

**Comment by pjaudiomv** [comment]
i just tested with an Samsung S6 Active on android 7.0 with chrome and works fine. maybe its an 8.0 (oreo) thing, i have no current means to test on 8.0 as well though.

**Comment by pjaudiomv** [comment]
lol nice

**Comment by pjaudiomv** [comment]
I had to do that with my iphone safari to reflect changes sometimes as well, that or go into private mode

**Comment by californiasteve** [comment]
Cool, like the icon for moving it.

**Comment by radius314** [comment]
Probably need to version the JavaScript and css.

**Comment by pjaudiomv** [comment]
yes or a file hash but that may be excessive
