### ISSUE TITLE
incoming call notification

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#99]
**Describe the bug**
when calling helpline with sms to volunteer option set an sms gets sent for every helpline volunteer thats on the schedule untill someone picks up. 

**What version are you running**
latest unstable

**To Reproduce**
set sms to volunteer option enabled
set multiple volunteers on schedule
call helpline and have no one pickup to cycle through the multiple volunteers
if option is set to loop every time it loops over same volunteer another txt gets sent

**Screenshot**
![img_8449](https://user-images.githubusercontent.com/34245618/42794235-c67f8e26-894b-11e8-992e-ec0d3abec925.PNG)

**Expected behavior**
only one txt gets sent alerting the Primary Contact Number of the callers number per duration of the call

**Comment by radius314** [comment]
The primary contact number should not get any texts whatsoever.  Only the volunteer that is being called.

**Comment by pjaudiomv** [comment]
Yes my bad I realized this after I posted, however each caller that gets tried the volunteer gets another txt within the same call

**Comment by pjaudiomv** [comment]
primary contact number is only for voicemail messages, sms to volunteer....gos to volunteer

**Comment by radius314** [comment]
correct... if you are looping forever, then it will send a text for each incoming call.  that is by design.

**Comment by pjaudiomv** [comment]
if only two volunteers are set for given time and have loop forever set, every time it loops through that volunteer they get another txt.

**Comment by pjaudiomv** [comment]
gotcha ok cool, yea dont hate the newcomer pick up the damn phone. got it

**Comment by radius314** [comment]
correct... that is the design.

**Comment by pjaudiomv** [comment]
sweet this can be closed then, thanks for clarification

**Comment by radius314** [comment]
when the dial-out happens, there is no real tracking of state of that call, other than a tracking integer.  because of this, there is no way to keep track of whether someone already got a call or not.

**Comment by radius314** [comment]
and with that, no way to prevent a 2nd text from flowing out.

**Comment by pjaudiomv** [comment]
gotcha

**Comment by radius314** [comment]
one thing that may come up in the future is in some of the larger service bodies (10 or more volunteers), is given others a chance to be first.  right now you can only sort the schedule in a single dimension.  what we could do is add another routing strategy to do random and then voicemail.  this would require keeping track of those that have already gotten a call and not redialing them.  this gets into state management (which we've avoided up until this point), minus session cookies introduced in beta3.

**Comment by radius314** [comment]
once this state management is in place, it becomes more viable to do things like, text only once if your routing strategy is loop foerver.

**Comment by pjaudiomv** [comment]
good to know, a random then voicemail feature could certainly be cool in the future. but the clarification on how by design this operated made total sense.

**Comment by radius314** [comment]
FB messenger integration uses redis for state management, however it's going to be split off into it's own project after yap 2.0 is released.  yap 2.1 will have an api key model for allowing such integrations.  with that, i'm really trying to avoid having any kind of datastore for Yap at the moment.  thankfully i was able to resolve a lot of the state related items with session cookies.  with the dialing aspect, because it happens in an async manner, i haven't quite figured out how to deal with this.
